name: Build and Release Telegram Bot API

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Clone Vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git telegram-bot-api/vcpkg

      - name: Bootstrap Vcpkg
        run: |
          cd telegram-bot-api/vcpkg
          ./bootstrap-vcpkg.bat

      - name: Install Dependencies
        run: |
          cd telegram-bot-api/vcpkg
          ./vcpkg.exe install gperf:x64-windows openssl:x64-windows zlib:x64-windows

      - name: Build Telegram Bot API
        run: |
          cd telegram-bot-api
          if (Test-Path build) { Remove-Item build -Force -Recurse }
          mkdir build
          cd build
          cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=.. -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
          cmake --build . --target install --config Release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: telegram-bot-api-binaries
          path: telegram-bot-api/bin/telegram-bot-api*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: telegram-bot-api-binaries

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Automated release of Telegram Bot API binaries.
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: telegram-bot-api/bin/telegram-bot-api*
          asset_name: telegram-bot-api-binary.exe
          asset_content_type: application/octet-stream
